version: 2.1
orbs:
  go: circleci/go@1.7.3
jobs:
  build_and_test:
    executor: 
      name: go/default
      tag: '1.22.0'

    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true

      - persist_to_workspace:
          root: ~/go-daraja
          paths:
            - "."

workflows:
  build:
    jobs:
      - build_and_test
          


