version: 2.1
orbs:
  go: circleci/go@1.7.3
jobs:
  build_and_test:
    executor: 
      name: go/default
      tag: '1.22.0'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: list dirs
          command: ls -al
      - go/test:
          covermode: atomic
          failfast: false
          race: false
      - persist_to_workspace:
          root: ~/project
          paths:
            - "."
workflows:
  build:
    jobs:
      - build_and_test
          


