version: 2.1
orbs:
  go: circleci/go@1.7.3
jobs:
  build_and_test:
    executor: 
      name: go/default
      tag: '1.22.0'
    steps:
      - checkout
      - run:
          name: create .env file
          command: |
            echo "DARAJA_ENVIRONMENT=$DARAJA_ENVIRONMENT" >> ./pkg/handler/.env
            echo "DARAJA_CONSUMER_KEY=$DARAJA_CONSUMER_KEY" >> ./pkg/handler/.env
            echo "DARAJA_CONSUMER_SECRET=$DARAJA_CONSUMER_SECRET" >> ./pkg/handler/.env
            echo "DARAJA_BUSINESS_SHORT_CODE=$DARAJA_BUSINESS_SHORT_CODE" >> ./pkg/handler/.env
            echo "DARAJA_PASS_KEY=$DARAJA_PASS_KEY" >> ./pkg/handler/.env
            echo "DARAJA_TRANSACTION_TYPE=$DARAJA_TRANSACTION_TYPE" >> ./phandler/kg/.env
            echo "DARAJA_CALL_BACK_URL=$DARAJA_CALL_BACK_URL" >> ./pkg/handler/.env
            echo "DARAJA_PARTY_B=$DARAJA_PARTY_B" >> ./pkg/handler/.env
            echo "DARAJA_TIMESTAMP=$DARAJA_TIMESTAMP" >> ./pkg/handler/.env
            echo "DARAJA_ACCOUNT_REF=$DARAJA_ACCOUNT_REF" >> ./pkg/handler/.env
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
      - run:
          name: list dirs
          command: ls -la /home/circleci
      - run:
          name: delete .env file
          command: rm -rf .env
      - persist_to_workspace:
          root: ~/project
          paths:
            - "."
workflows:
  build:
    jobs:
      - build_and_test:
          context: go-daraja-test-envs
          


