name: go-daraja-test
on:
  push:
    branches:
      - develop
		- master
jobs:
  go-daraja-test:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
		 - name: setting golang environmnet
		   uses: actions/setup-go@v3
			with:
			  go-version: "1.22.x"

	    - name: run go-daraja test
		   run: ./run.sh