name: Build docs (MkDocs)

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

concurrency:
  group: mkdocs-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and theme
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material pymdown-extensions

      - name: Build docs
        run: mkdocs build --strict

      - name: Upload built site artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkdocs-site
          path: site
          if-no-files-found: error
          retention-days: 7
